$(document).ready(function(){
    $('input.autocomplete').autocomplete({
      data: colleges,
    });
  });
  
const colleges =  {
    "University of Alaska"  : null,
    "Alaska Christian College"  : null,
    "National Park Community College"  : null,
    "University of Alaska Fairbanks"  : null,
    "University of Arkansas - Fort Smith"  : null,
    "Alabama A&M University"  : null,
    "Athens State University"  : null,
    "Auburn University"  : null,
    "Auburn University at Montgomery"  : null,
    "Birmingham-Southern College"  : null,
    "Calhoun Community College"  : null,
    "Enterprise State Community College"  : null,
    "Faulkner State Community College"  : null,
    "Gadsden State Community College"  : null,
    "Huntingdon College"  : null,
    "Jacksonville State University"  : null,
    "Lurleen B. Wallace Community College"  : null,
    "University of Montevallo"  : null,
    "Northeast Alabama Community College"  : null,
    "Northwest-Shoals Community College"  : null,
    "Oakwood University"  : null,
    "Samford University"  : null,
    "Southeastern Bible College"  : null,
    "University of South Alabama"  : null,
    "Trenholm State Technical College"  : null,
    "Troy University"  : null,
    "Tuskegee University"  : null,
    "University of Alabama"  : null,
    "University of Alabama at Birmingham"  : null,
    "University of Alabama in Huntsville"  : null,
    "University of North Alabama"  : null,
    "Snead State Community College"  : null,
    "Arkansas Northeastern College"  : null,
    "Arkansas State University"  : null,
    "Arkansas Tech University"  : null,
    "Central Baptist College"  : null,
    "Harding University"  : null,
    "Hendrix College"  : null,
    "Henderson State University"  : null,
    "John Brown University"  : null,
    "Lyon College"  : null,
    "Mid-South Community College"  : null,
    "North Arkansas College"  : null,
    "Northwest Arkansas Community College"  : null,
    "Northwest Technical Institute"  : null,
    "Ouachita Baptist University"  : null,
    "University of the Ozarks"  : null,
    "Phillips Community College U of A"  : null,
    "Pulaski Technical College"  : null,
    "Southern Arkansas University Magnolia"  : null,
    "Southeast Arkansas College"  : null,
    "University of Arkansas Community College Batesville"  : null,
    "University of Arkansas at Little Rock"  : null,
    "University of Arkansas for Medical Sciences"  : null,
    "University of Arkansas at Pine Bluff"  : null,
    "University of Arkansas"  : null,
    "University of Central Arkansas"  : null,
    "Williams Baptist College"  : null,
    "University of Arizona"  : null,
    "Arizona State University"  : null,
    "Arizona Western College"  : null,
    "Bryan University"  : null,
    "Central Arizona College"  : null,
    "Glendale Community College"  : null,
    "Grand Canyon University"  : null,
    "Maricopa Community Colleges"  : null,
    "Mesa Community College"  : null,
    "Northern Arizona University"  : null,
    "Northland Pioneer College"  : null,
    "University of Phoenix"  : null,
    "Phoenix College"  : null,
    "Pima Community College"  : null,
    "Prescott College"  : null,
    "Rio Salado College"  : null,
    "South Mountain Community College"  : null,
    "University of Advancing Technology"  : null,
    "Yavapai College"  : null,
    "Academy of Arts University"  : null,
    "Adance Computing Institute"  : null,
    "Acupuncture & Integrative Medicine College"  : null,
    "Alliant International University"  : null,
    "Allied American University"  : null,
    "Anaheim University"  : null,
    "Angeles College"  : null,
    "Antioch University Los Angeles"  : null,
    "Argosy University"  : null,
    "Art Center College of Design"  : null,
    "The Art Institute"  : null,
    "Ashford University"  : null,
    "ATI College"  : null,
    "Antelope Valley College"  : null,
    "Bakersfield College"  : null,
    "Barstow Community College"  : null,
    "Berkeley University of California"  : null,
    "Berkeley City College"  : null,
    "Brandman University"  : null,
    "Butte College"  : null,
    "Cabrillo College"  : null,
    "California Institute of the Arts"  : null,
    "California Baptist University"  : null,
    "California Lutheran University"  : null,
    "California Miramar University"  : null,
    "California Polytechnic State University"  : null,
    "California State University"  : null,
    "California Institute of Technology"  : null,
    "Canada College"  : null,
    "College of the Canyons"  : null,
    "California College of the Arts"  : null,
    "California Community Colleges Chanellor's Office"  : null,
    "City College of San Francisco"  : null,
    "Cerritos College"  : null,
    "Cerro Coso Community College"  : null,
    "Claremont Graduate University"  : null,
    "Chaffey College"  : null,
    "Chapman University"  : null,
    "California Institute of Integral Studies"  : null,
    "Citrus College"  : null,
    "The Claremont Colleges"  : null,
    "Claremont McKenna College"  : null,
    "Copper Mountain College"  : null,
    "Cogswell Polytechnical College"  : null,
    "College of San Mateo"  : null,
    "College of the Desert"  : null,
    "El Camino College Compton Center"  : null,
    "Contra Costa College"  : null,
    "College of the Sequoias"  : null,
    "Crafton Hills College"  : null,
    "California State University Bakersfield"  : null,
    "California State University Channel Islands"  : null,
    "California State University Dominguez Hills"  : null,
    "California State University East Bay"  : null,
    "Fresno State"  : null,
    "California State University Long Beach"  : null,
    "California State University Monterey Bay"  : null,
    "California State University Northridge"  : null,
    "California State Polytechnic University Pomona"  : null,
    "California State University Sacramento"  : null,
    "California State University San Bernardino"  : null,
    "California State University San Marcos"  : null,
    "California State University Stanislaus"  : null,
    "Cuesta College"  : null,
    "Cuyamaca College"  : null,
    "California Western School of Law San Diego"  : null,
    "Cypress College"  : null,
    "DeAnza College"  : null,
    "San Joaquin Delta College"  : null,
    "Dominican University of California"  : null,
    "Dominican School of Philosophy and Theology"  : null,
    "Diablo Valley College"  : null,
    "East Los Angeles College"  : null,
    "El Camino College"  : null,
    "Ex'pression College"  : null,
    "Foothill-De Anza Community College District"  : null,
    "Fashion Institute of Design & Merchandising"  : null,
    "Fielding Graduate University"  : null,
    "Foothill College"  : null,
    "Fresno Pacific University"  : null,
    "Fresno City College"  : null,
    "Frederick Taylor University"  : null,
    "Fullerton College"  : null,
    "Fuller Theological Seminary"  : null,
    "California State University Fullerton"  : null,
    "Gavilan College"  : null,
    "Golden Gate Baptist Theological Seminary"  : null,
    "Glendale Community College"  : null,
    "Gnomon School of Visual Effects"  : null,
    "Columbia College"  : null,
    "Golden West College"  : null,
    "Grossmont College"  : null,
    "Allan Hancock College"  : null,
    "Hartnell College"  : null,
    "Henley-Putnam University"  : null,
    "Harvey Mudd College"  : null,
    "Holy Names University"  : null,
    "Humboldt State University"  : null,
    "Humphreys College"  : null,
    "Imperial Valley College"  : null,
    "International Sports Sciences Association"  : null,
    "International Technological University"  : null,
    "Irvine Valley College"  : null,
    "William Jessup University"  : null,
    "John F. Kennedy University"  : null,
    "Keck Graduate Institute"  : null,
    "Mount Saint Mary's College"  : null,
    "Los Angeles Community College District"  : null,
    "Los Angeles City College"  : null,
    "Los Angeles Harbor College"  : null,
    "Los Angeles Mission College"  : null,
    "Laney College"  : null,
    "Los Angeles Southwest College"  : null,
    "La Sierra University"  : null,
    "Las Positas College"  : null,
    "Los Angeles Trade-Tech Community College"  : null,
    "Laurus College"  : null,
    "Los Angeles Valley College"  : null,
    "University of La Verne"  : null,
    "UCLA School of Law"  : null,
    "Long Beach City College"  : null,
    "Life Chiropractic College West"  : null,
    "Loma Linda University"  : null,
    "Loyola Marymount University"  : null,
    "Los Medanos College"  : null,
    "Los Rios Community College District"  : null,
    "Lake Tahoe Community College"  : null,
    "College of Marin"  : null,
    "Marymount California University"  : null,
    "The Master's College"  : null,
    "Merced Community College"  : null,
    "Mills College"  : null,
    "MiraCosta College"  : null,
    "Modesto Junior College"  : null,
    "Mount San Jacinto College"  : null,
    "Mount San Antonio College"  : null,
    "Napa Valley College"  : null,
    "Notre Dame de Namur University"  : null,
    "NewSchool of Architecture and Design"  : null,
    "Norco College"  : null,
    "Naval Postgraduate School"  : null,
    "Ohlone College"  : null,
    "Orange Coast College"  : null,
    "Otis College of Art and Design"  : null,
    "Occidental College"  : null,
    "University of the Pacific"  : null,
    "Pacific College of Oriental Medicine"  : null,
    "Palomar College"  : null,
    "Pasadena City College"  : null,
    "Pepperdine University"  : null,
    "Peralta Community College District"  : null,
    "Pierce College"  : null,
    "Pitzer College"  : null,
    "Pacific Lutheran Theological Seminary"  : null,
    "Point Loma Nazarene University"  : null,
    "Pomona College"  : null,
    "Porterville College"  : null,
    "Pacific School of Religion"  : null,
    "Riverside City College"  : null,
    "Riverside Community College District"  : null,
    "University of Redlands"  : null,
    "College of the Redwoods"  : null,
    "Rio Hondo College"  : null,
    "Rosemead College"  : null,
    "Santa Ana College"  : null,
    "Saddleback College"  : null,
    "University of San Diego"  : null,
    "Santa Rosa Junior College"  : null,
    "Santa Barbara City College"  : null,
    "School of Continuing Education"  : null,
    "Scripps College"  : null,
    "Santa Clara University"  : null,
    "Southern California University of Health Sciences"  : null,
    "San Diego City College"  : null,
    "San Diego Mesa College"  : null,
    "San Diego State University"  : null,
    "San Francisco State University"  : null,
    "Shasta College"  : null,
    "The Institute of Buddhist Studies"  : null,
    "Sierra College"  : null,
    "Simpson University"  : null,
    "College of the Siskiyous"  : null,
    "San Jose State University"  : null,
    "Starr King School for the Ministry"  : null,
    "Skyline College"  : null,
    "Santa Monica College"  : null,
    "San Mateo County Community College"  : null,
    "Soka University of America"  : null,
    "Solano Community College"  : null,
    "Sonoma State University"  : null,
    "Stanford University"  : null,
    "Saint Mary's College"  : null,
    "Taft College"  : null,
    "Touro University California"  : null,
    "University of California Davis"  : null,
    "University of California Hastings College of the Law"  : null,
    "University of California Irvine"  : null,
    "University of California Los Angeles"  : null,
    "University of California Los Angeles Extension"  : null,
    "University of California Merced"  : null,
    "University of California"  : null,
    "University of California Press"  : null,
    "University of California Riverside"  : null,
    "University of California Santa Barbara"  : null,
    "University of California Santa Cruz"  : null,
    "University of California Santa Cruz Silicon Valley Extension"  : null,
    "University of California San Diego"  : null,
    "University of California San Francisco"  : null,
    "University of California"  : null,
    "University of the Pacific"  : null,
    "University of Southern California"  : null,
    "University of San Francisco"  : null,
    "San Bernardino Valley College"  : null,
    "Ventura College"  : null,
    "Victor Valley College"  : null,
    "West Coast Baptist College"  : null,
    "Western University of Health Sciences"  : null,
    "Westmont College"  : null,
    "West Valley College"  : null,
    "West Hills Community College District"  : null,
    "Whittier College"  : null,
    "West Los Angeles College"  : null,
    "Yuba Community College District"  : null,
    "Yosemite Community College District"  : null,
    "Unitek College"  : null,
    "Vanguard University"  : null,
    "Southwestern College"  : null,
    "Monterey Institute of International Studies"  : null,
    "Adams State University"  : null,
    "Auraria Higher Education Center"  : null,
    "Aims Community College"  : null,
    "Arapahoe Community College"  : null,
    "Community College of Aurora"  : null,
    "Community College of Denver"  : null,
    "Colorado Heights University"  : null,
    "University of Colorado Boulder"  : null,
    "Colorado College"  : null,
    "Colorado Mesa University"  : null,
    "Colorado State University"  : null,
    "Colorado State University-Pueblo"  : null,
    "University of Denver"  : null,
    "Fort Lewis College"  : null,
    "Front Range Community College"  : null,
    "Jones International University"  : null,
    "Colorado School of Mines"  : null,
    "Metropolitan State University of Denver"  : null,
    "Naropa University"  : null,
    "Pikes Peak Community College"  : null,
    "Pueblo Community College"  : null,
    "Redstone College"  : null,
    "Regis University"  : null,
    "University of the Rockies"  : null,
    "Red Rocks Community College"  : null,
    "William Howard Taft University"  : null,
    "University Corporation for Atmospheric Research"  : null,
    "University of Colorado Colorado Springs"  : null,
    "University of Colorado Denver"  : null,
    "University of Northern Colorado"  : null,
    "University of Colorado"  : null,
    "Western State Colorado University"  : null,
    "Albertus Magnus College"  : null,
    "Asnuntuck Community College"  : null,
    "Connecticut College"  : null,
    "Eastern Connecticut State University"  : null,
    "Fairfield University"  : null,
    "Goodwin College"  : null,
    "University of Hartford"  : null,
    "Hartford Seminary"  : null,
    "University of New Haven"  : null,
    "Queens University of Charlotte"  : null,
    "Quinebaug Valley Community College"  : null,
    "Sacred Heart University"  : null,
    "Southern Connecticut State University"  : null,
    "Three Rivers Community College"  : null,
    "Trinity College"  : null,
    "Tunxis Community College"  : null,
    "University of Connecticut Health Center"  : null,
    "University of Connecticut"  : null,
    "University of Saint Joseph Connecticut"  : null,
    "Western Connecticut State University"  : null,
    "Wesleyan University"  : null,
    "Yale University"  : null,
    "American University"  : null,
    "Carnegie Institution for Science"  : null,
    "The Catholic University of America"  : null,
    "Gallaudet University"  : null,
    "Georgetown University"  : null,
    "The George Washington University"  : null,
    "Howard University"  : null,
    "Johns Hopkins School of Advanced International Studies"  : null,
    "University of California Washington Center"  : null,
    "University of the District of Columbia"  : null,
    "Delaware State University"  : null,
    "Delaware Technical Community College"  : null,
    "Goldey-Beacom College"  : null,
    "University of Delaware"  : null,
    "Wesley College"  : null,
    "Wilmington University"  : null,
    "Carlos Albizu University"  : null,
    "Acupuncture Massage College"  : null,
    "Atlantic Institute of Oriental Medicine"  : null,
    "Barry University"  : null,
    "Broward College"  : null,
    "College of Central Florida"  : null,
    "Chipola College"  : null,
    "Bethune-Cookman University"  : null,
    "Dade Medical College"  : null,
    "Daytona State College"  : null,
    "Eckerd College"  : null,
    "Edison State College"  : null,
    "Embry-Riddle Aeronautical University"  : null,
    "Everglades University"  : null,
    "Florida Atlantic University"  : null,
    "Florida Gulf Coast University"  : null,
    "Florida Institute of Technology"  : null,
    "Florida International University"  : null,
    "Flagler College"  : null,
    "Florida Southern College"  : null,
    "Florida National University"  : null,
    "Florida State College at Jacksonville"  : null,
    "Florida State University"  : null,
    "Gulf Coast State College"  : null,
    "Hillsborough Community College"  : null,
    "Jacksonville University"  : null,
    "Keiser University"  : null,
    "Loraines Academy Incorporated"  : null,
    "Lake Sumter State College"  : null,
    "Lynn University"  : null,
    "Millennia Atlantic University"  : null,
    "Miami Dade College"  : null,
    "University of Miami"  : null,
    "Miami International University of Art and Design"  : null,
    "New College of Florida"  : null,
    "North Florida Community College"  : null,
    "Nova Southeastern University"  : null,
    "National University of Health Sciences"  : null,
    "Northwest Florida State College"  : null,
    "Palm Beach State College"  : null,
    "Palm Beach Atlantic University"  : null,
    "Pensacola State College"  : null,
    "Pasco-Hernando State College"  : null,
    "Ringling College of Art and Design"  : null,
    "Rollins College"  : null,
    "Saint Leo University"  : null,
    "State College of Florida"  : null,
    "Seminole State College of Florida"  : null,
    "Santa Fe College"  : null,
    "South Florida State College"  : null,
    "Space Coast Health Institute"  : null,
    "Saint Petersburg College"  : null,
    "Stetson University"  : null,
    "Saint Thomas University"  : null,
    "Saint Vincent de Paul Regional Seminary"  : null,
    "Traviss Career Center"  : null,
    "University of Central Florida"  : null,
    "University of Florida"  : null,
    "University of North Florida"  : null,
    "University of South Florida"  : null,
    "University of South Florida Sarasota-Manatee"  : null,
    "University of South Florida Saint Petersburg"  : null,
    "University of Tampa"  : null,
    "University of West Florida"  : null,
    "Valencia College"  : null,
    "Warner University"  : null,
    "Webber International University"  : null,
    "Agnes Scott College"  : null,
    "Albany Technical College"  : null,
    "Armstrong Atlantic State University"  : null,
    "Atlanta Technical College"  : null,
    "Atlanta Metropolitan State College"  : null,
    "Berry College"  : null,
    "Carver College"  : null,
    "Child Care Education Institute"  : null,
    "Central Georgia Technical College"  : null,
    "Clayton State University"  : null,
    "Columbus State University"  : null,
    "Columbus Technical College"  : null,
    "Covenant College"  : null,
    "Dalton State"  : null,
    "Darton State College"  : null,
    "East Georgia State College"  : null,
    "Emory University"  : null,
    "Georgia Institute of Technology"  : null,
    "Georgia College"  : null,
    "Georgia Southern University"  : null,
    "Georgia Gwinnett College"  : null,
    "Georgia Perimeter College"  : null,
    "Georgia Regents University Augusta"  : null,
    "Georgia State University"  : null,
    "Georgia South Western State University"  : null,
    "Interactive College of Technology"  : null,
    "Atlanta's John Marshall Law School"  : null,
    "Kennesaw State University"  : null,
    "Lanier Technical College"  : null,
    "Life University"  : null,
    "Mercer University"  : null,
    "Middle Georgia State College"  : null,
    "Morehouse College"  : null,
    "Morehouse School of Medicine"  : null,
    "North Georgia Technical College"  : null,
    "Oglethorpe University"  : null,
    "Okefenokee Technical College"  : null,
    "Paine College"  : null,
    "Pfeiffer University"  : null,
    "Piedmont College"  : null,
    "Reinhardt University"  : null,
    "Savannah State University"  : null,
    "Savannah College of Art and Design"  : null,
    "Shorter University"  : null,
    "Southeastern Technical College"  : null,
    "Spelman College"  : null,
    "Southern Polytechnic State University"  : null,
    "Thomas University"  : null,
    "University of Georgia"  : null,
    "University of North Georgia"  : null,
    "University System of Georgia"  : null,
    "Valdosta State University"  : null,
    "University of West Georgia"  : null,
    "Wiregrass Georgia Technical College"  : null,
    "Brigham Young University Hawaii"  : null,
    "Chaminade University"  : null,
    "University of Hawaii at Manoa"  : null,
    "Mid-Pacific Institute"  : null,
    "AIB College of Business"  : null,
    "Central College"  : null,
    "Coe College"  : null,
    "Cornell College"  : null,
    "Des Moines Area Community College"  : null,
    "Dordt College"  : null,
    "Drake University"  : null,
    "Divine Word College"  : null,
    "Eastern Iowa Community Colleges"  : null,
    "Grinnell College"  : null,
    "Hawkeye Community College"  : null,
    "Iowa State University"  : null,
    "Iowa Central Community College"  : null,
    "Iowa Wesleyan College"  : null,
    "Iowa Western Community College"  : null,
    "Kaplan University"  : null,
    "Kirkwood Community College"  : null,
    "La' James College"  : null,
    "Loras College"  : null,
    "Luther College"  : null,
    "Maharishi University of Management"  : null,
    "Northeast Iowa Community College"  : null,
    "Palmer College of Chiropractic"  : null,
    "Saint Ambrose University"  : null,
    "Simpson College"  : null,
    "Southwestern Community College"  : null,
    "Univeristy of Iowa"  : null,
    "Upper Iowa University"  : null,
    "University of Northern Iowa"  : null,
    "Wartburg College"  : null,
    "Waldorf College"  : null,
    "Boise State University"  : null,
    "Brigham Young University Idaho"  : null,
    "The College of Idaho"  : null,
    "College of Southern Idaho"  : null,
    "Idaho State University"  : null,
    "University of Idaho"  : null,
    "Augustana College"  : null,
    "Aurora University"  : null,
    "Benedictine University"  : null,
    "Bradley University"  : null,
    "City Colleges of Chicago"  : null,
    "The University of Chicago Booth School of Business"  : null,
    "College of Lake County"  : null,
    "College of DuPage"  : null,
    "Columbia College Chicago"  : null,
    "Danville Area Community College"  : null,
    "DePaul University"  : null,
    "Dominican University"  : null,
    "Eastern Illinois University"  : null,
    "Elmhurst College"  : null,
    "Governors State"  : null,
    "Greenville College"  : null,
    "The Hadley School for the Blind"  : null,
    "Harper College"  : null,
    "Heartland Community College"  : null,
    "Illinois Central College"  : null,
    "Illinois College of Optometry"  : null,
    "Illinois Institute of Technology"  : null,
    "University of Illinois at Urbana-Champaign"  : null,
    "Illinois State University"  : null,
    "Illinois Mathematics and Science Academy"  : null,
    "Illinois Valley Community College"  : null,
    "Illinois Wesleyan University"  : null,
    "John A. Logan College"  : null,
    "Joliet Junior College"  : null,
    "The John Marshall Law School"  : null,
    "Judson University"  : null,
    "Kaskaskia College"  : null,
    "Kankakee Community College"  : null,
    "IIT Chicago-Kent College of Law"  : null,
    "Kishwaukee College"  : null,
    "Knox College"  : null,
    "Lake Forest College"  : null,
    "Lakeview College of Nursing"  : null,
    "Lewis and Clark Community College"  : null,
    "Lewis University"  : null,
    "Lincoln Land Community College"  : null,
    "Loyola University Chicago"  : null,
    "Midwestern Career College"  : null,
    "McHenry County College"  : null,
    "McKendree University"  : null,
    "Midwestern University"  : null,
    "Monmouth College"  : null,
    "Moraine Valley Community College"  : null,
    "Morton College"  : null,
    "Northeastern Illinois University"  : null,
    "Northern Illinois University"  : null,
    "National Louis University"  : null,
    "North Park University"  : null,
    "Northwestern University"  : null,
    "Oakton Community College"  : null,
    "Olivet Nazarene University"  : null,
    "Chicago ORT Technical Institute"  : null,
    "Parkland College"  : null,
    "Prairie State College"  : null,
    "Principia College"  : null,
    "Resurrection University"  : null,
    "Robert Morris University Illinois"  : null,
    "Rockford University"  : null,
    "Rock Valley College"  : null,
    "Roosevelt University"  : null,
    "Rosalind Franklin University"  : null,
    "Saint Anthony College of Nursing"  : null,
    "School of the Art Institute of Chicago"  : null,
    "Saint Francis Medical Center College of Nursing"  : null,
    "Shawnee Community College"  : null,
    "Southeastern Illinois College"  : null,
    "Southern Illinois University"  : null,
    "Southern Illinois University Edwardsville"  : null,
    "Spoon River College"  : null,
    "South Suburban College"  : null,
    "University of Saint Francis"  : null,
    "Southwestern Illinois College"  : null,
    "Saint Xavier University"  : null,
    "Trinity Christian College"  : null,
    "University of Chicago"  : null,
    "University of Illinois at Chicago"  : null,
    "University of Illinois"  : null,
    "University of Illinois Springfield"  : null,
    "University of Illinois at Urbana-Champaign"  : null,
    "Waubonsee Community College"  : null,
    "Wheaton College"  : null,
    "Western Illinois University"  : null,
    "Saint John's College"  : null,
    "Anabaptist Mennonite Biblical Seminary"  : null,
    "Anderson University"  : null,
    "Bethel College Indiana"  : null,
    "Brown Mackie College"  : null,
    "Ball State University"  : null,
    "Butler University"  : null,
    "DePauw University"  : null,
    "Earlham College"  : null,
    "University of Evansville"  : null,
    "Goshen College"  : null,
    "Grace College and Seminary"  : null,
    "Hanover College"  : null,
    "Harrison College"  : null,
    "Holy Cross College"  : null,
    "Indiana University"  : null,
    "Indiana State University"  : null,
    "Indiana Wesleyan University"  : null,
    "Indiana University - Purdue University Fort Wayne"  : null,
    "Indiana University"  : null,
    "Indiana University Bloomington"  : null,
    "Indiana University East"  : null,
    "Indiana University Northwest"  : null,
    "Indiana University - Purdue University Indianapolis"  : null,
    "Indiana University Southeast"  : null,
    "Indiana University South Bend"  : null,
    "Ivy Tech Community College"  : null,
    "Manchester University"  : null,
    "Marian University Indianapolis"  : null,
    "University of Notre Dame"  : null,
    "Oakland City University"  : null,
    "Purdue University North Central"  : null,
    "Purdue University"  : null,
    "Purdue University Calumet"  : null,
    "Rose-Hulman Institute of Technology"  : null,
    "Saint Mary's College"  : null,
    "Trine University"  : null,
    "University of Indianapolis"  : null,
    "University of Southern Indiana"  : null,
    "Valparaiso University"  : null,
    "Wabash College"  : null,
    "Benedictine College"  : null,
    "Butler Community College"  : null,
    "Emporia State University"  : null,
    "Fort Hays State University"  : null,
    "Flint Hills Technical College"  : null,
    "Fort Scott Community College"  : null,
    "Garden City Community College"  : null,
    "Hesston College"  : null,
    "Highland Community College"  : null,
    "Johnson County Community College"  : null,
    "Kansas City Kansas Community College"  : null,
    "Kansas State University"  : null,
    "The University of Kansas"  : null,
    "McPherson College"  : null,
    "Neosho County Community College"  : null,
    "Newman University"  : null,
    "Pittsburg State University"  : null,
    "Saint Paul School of Theology and Ministry"  : null,
    "Sterling College"  : null,
    "University of Saint Mary"  : null,
    "Washburn University"  : null,
    "Washburn University School of Law"  : null,
    "Wichita State University"  : null,
    "Asbury University"  : null,
    "Bellarmine University"  : null,
    "Berea College"  : null,
    "Centre College"  : null,
    "Eastern Kentucky University"  : null,
    "Frontier Nursing University"  : null,
    "Georgetown College"  : null,
    "Kentucky Community and Technical College System"  : null,
    "Kentucky Christian University"  : null,
    "Kentucky State University"  : null,
    "Lindsey Wilson College"  : null,
    "The University of Louisville"  : null,
    "Midway College"  : null,
    "Morehead State University"  : null,
    "Murray State University"  : null,
    "Northern Kentucky University"  : null,
    "The Southern Baptist Theological Seminary"  : null,
    "Saint Catharine College"  : null,
    "Sullivan University"  : null,
    "University of the Cumberlands"  : null,
    "Western Kentucky University"  : null,
    "Bossier Parish Community College"  : null,
    "Centenary College of Louisiana"  : null,
    "Louisiana Tech University"  : null,
    "Louisiana Culinary Institute"  : null,
    "University of Louisiana Lafayette"  : null,
    "Loyola University New Orleans"  : null,
    "Louisiana State University"  : null,
    "Louisiana State University - Eunice"  : null,
    "LSU Health Sciences Center - New Orleans"  : null,
    "LSU Health Sciences Center - New Orleans"  : null,
    "Louisiana State University System"  : null,
    "Nicholls State University"  : null,
    "New Orleans Baptist Theological Seminary"  : null,
    "Nunez Community College"  : null,
    "Southeastern Louisiana University"  : null,
    "Southern University"  : null,
    "Tulane University"  : null,
    "University of Louisiana at Monroe"  : null,
    "University of New Orleans"  : null,
    "Xavier University of Louisiana"  : null,
    "Amherst College"  : null,
    "Assumption College"  : null,
    "Babson College"  : null,
    "Boston College"  : null,
    "Bentley University"  : null,
    "Berklee College of Music"  : null,
    "Berkshire Community College"  : null,
    "The Boston Conservatory"  : null,
    "Brandeis University"  : null,
    "Bridgewater State University"  : null,
    "Boston University"  : null,
    "Cambridge College"  : null,
    "Clark University"  : null,
    "Curry College"  : null,
    "Elms College"  : null,
    "Emerson College"  : null,
    "Emmanuel College"  : null,
    "Endicott College"  : null,
    "Fitchburg State University"  : null,
    "Framingham State University"  : null,
    "Gordon Conwell Theological Seminary"  : null,
    "Gordon College"  : null,
    "Hampshire College"  : null,
    "Harvard University"  : null,
    "Harvard Business School"  : null,
    "College of the Holy Cross"  : null,
    "Lesley University"  : null,
    "Massachusetts Maritime Academy"  : null,
    "Massachusetts Department of Higher Education"  : null,
    "Massachusetts College of Art and Design"  : null,
    "MassBay Community College"  : null,
    "Marine Biological Laboratory"  : null,
    "Merrimack Education Center"  : null,
    "Merrimack College"  : null,
    "MGH Institute of Health Professions"  : null,
    "Milton Academy"  : null,
    "Massachusetts Institute of Technology"  : null,
    "Montserrat College of Art"  : null,
    "Mount Ida College"  : null,
    "Mount Holyoke College"  : null,
    "Middlesex Community College"  : null,
    "Middlesex School"  : null,
    "North Bennet Street School"  : null,
    "New England Law - Boston"  : null,
    "Northeastern University"  : null,
    "Olin College of Engineering"  : null,
    "Salem State University"  : null,
    "Simmons College"  : null,
    "Smith College"  : null,
    "Spa Tech Institute"  : null,
    "Springfield College"  : null,
    "Springfield Technical Community College"  : null,
    "Suffolk University"  : null,
    "Boston Architectural College"  : null,
    "Tufts University"  : null,
    "University of Massachusetts Amherst"  : null,
    "University of Massachusetts Dartmouth"  : null,
    "University of Massachusetts Medical School"  : null,
    "University of Massachusetts"  : null,
    "University of Massachusetts Boston"  : null,
    "University of Massachusetts Lowell"  : null,
    "Wellesley College"  : null,
    "Wheaton College, Norton"  : null,
    "Wheelock College"  : null,
    "Williams College"  : null,
    "Western New England University"  : null,
    "Worcester State University"  : null,
    "Worcester Polytechnic Institute"  : null,
    "Anne Arundel Community College"  : null,
    "Baltimore City Community College"  : null,
    "Bowie State University"  : null,
    "Carroll Community College"  : null,
    "The Community College of Baltimore County"  : null,
    "Chesapeake College"  : null,
    "Coppin State University"  : null,
    "College of Southern Maryland"  : null,
    "Frederick Community College"  : null,
    "Frostburg State University"  : null,
    "Garrett College"  : null,
    "Goucher College"  : null,
    "Hagerstown Community College"  : null,
    "Harford Community College"  : null,
    "Hood College"  : null,
    "Howard Community College"  : null,
    "Johns Hopkins Bloomberg School of Public Health"  : null,
    "Johns Hopkins University"  : null,
    "Loyola University Maryland"  : null,
    "Montgomery Blair High School"  : null,
    "McDaniel College"  : null,
    "Maryland Institute College of Art"  : null,
    "Montgomery College"  : null,
    "Mount Saint Mary's University"  : null,
    "Maryland University of Integrative Health"  : null,
    "Prince George's Community College"  : null,
    "Salisbury University"  : null,
    "Sojourner-Douglass College"  : null,
    "Saint Mary's College of Maryland"  : null,
    "Saint James School"  : null,
    "Towson University"  : null,
    "University of Baltimore"  : null,
    "University of Maryland"  : null,
    "University of Maryland Baltimore County"  : null,
    "University of Maryland"  : null,
    "University of Maryland University College"  : null,
    "University System of Maryland"  : null,
    "United States Naval Academy"  : null,
    "Washington College"  : null,
    "Wor-Wic Community College"  : null,
    "Saint John's College"  : null,
    "Bates College"  : null,
    "Bowdoin College"  : null,
    "Central Maine Community College"  : null,
    "College of the Atlantic"  : null,
    "Colby College"  : null,
    "Husson University"  : null,
    "Maine Maritime Academy"  : null,
    "Northern Maine Community College"  : null,
    "Saint Joseph's College"  : null,
    "Southern Maine Community College"  : null,
    "University of Maine"  : null,
    "University of Maine Fort Kent"  : null,
    "University of Maine at Presque Isle"  : null,
    "University of New England"  : null,
    "Unity College"  : null,
    "York County Community College"  : null,
    "University of Main at Augusta"  : null,
    "Adrian College"  : null,
    "Albion College"  : null,
    "Alma College"  : null,
    "Alpena Community College"  : null,
    "Andrews University"  : null,
    "Aquinas College"  : null,
    "Baker College"  : null,
    "Bay College"  : null,
    "Calvin College"  : null,
    "Central Michigan University"  : null,
    "College for Creative Studies"  : null,
    "Cornerstone University"  : null,
    "Davenport University"  : null,
    "Delta College"  : null,
    "Douglas J. Aveda Institute"  : null,
    "Eastern Michigan University"  : null,
    "Ferris State University"  : null,
    "Finlandia University"  : null,
    "Grand Rapids Community College"  : null,
    "Grand Valley State University"  : null,
    "Henry Ford College"  : null,
    "Hillsdale College"  : null,
    "Hope College"  : null,
    "Jackson College"  : null,
    "Kettering University"  : null,
    "Kalamazoo Valley Community College"  : null,
    "Kalamazoo College"  : null,
    "Lake Michigan College"  : null,
    "Lansing Community College"  : null,
    "Lake Superior State University"  : null,
    "Lawrence Technological University"  : null,
    "Macomb Community College"  : null,
    "Marygrove College"  : null,
    "Monroe County Community College"  : null,
    "Michigan State University"  : null,
    "Michigan Technological University"  : null,
    "Northwestern Michigan College"  : null,
    "Northern Michigan University"  : null,
    "Oakland Univeristy"  : null,
    "Oakland Community College"  : null,
    "Saginaw Chippewa Tribal College"  : null,
    "Saginaw Valley State University"  : null,
    "University of Detroit Mercy"  : null,
    "University of Michigan-Flint"  : null,
    "University of Michigan"  : null,
    "Wayne State"  : null,
    "Washtenaw Community College"  : null,
    "Western Michigan University"  : null,
    "Alexandria Technical & Community College"  : null,
    "Anoka-Ramsey Community College"  : null,
    "Augsburg College"  : null,
    "Bemidji State University"  : null,
    "Bethel University"  : null,
    "Carleton College"  : null,
    "Century College"  : null,
    "Central Lakes College"  : null,
    "Concordia College"  : null,
    "Crown College"  : null,
    "College of Saint Benedict, Saint John's University"  : null,
    "Concordia University Saint Paul"  : null,
    "The College of Saint Scholastica"  : null,
    "Dakota County Technical College"  : null,
    "Gustavus Adolphus College"  : null,
    "Globe University"  : null,
    "Hamline University"  : null,
    "Inver Hills Community College"  : null,
    "Institute of Production and Recording"  : null,
    "Leech Lake Tribal College"  : null,
    "Luther Seminary"  : null,
    "Macalester College"  : null,
    "McNally Smith College of Music"  : null,
    "Mesabi Range College"  : null,
    "Metropolitan State University"  : null,
    "Minnesota State University Moorhead"  : null,
    "Minnesota State University Mankato"  : null,
    "North Hennepin Community College"  : null,
    "Normandale Community College"  : null,
    "Rasmussen College"  : null,
    "Ridgewater College"  : null,
    "Southwest Minnesota State University"  : null,
    "Saint Mary's University of Minnesota"  : null,
    "South Central College"  : null,
    "Saint Cloud State University"  : null,
    "Saint Olaf College"  : null,
    "University of Saint Thomas"  : null,
    "University of Minnesota"  : null,
    "United Theological Seminary of the Twin Cities"  : null,
    "University of Northwestern Saint Paul"  : null,
    "Walden University"  : null,
    "Winona State Unviversity"  : null,
    "Assemblies of God Theological Seminary"  : null,
    "Aquinas Institute of Theology"  : null,
    "A.T. Still University"  : null,
    "Avila University"  : null,
    "Columbia College"  : null,
    "Central Methodist University"  : null,
    "Crowder College"  : null,
    "Culver-Stockton College"  : null,
    "Drury University"  : null,
    "Evangel University"  : null,
    "Fontbonne University"  : null,
    "Hannibal-LaGrange"  : null,
    "Harris-Stowe State University"  : null,
    "Jefferson College"  : null,
    "Kansas City University of Medicine and Biosciences"  : null,
    "Lincoln University"  : null,
    "Lindenwood University"  : null,
    "Linn State Technical College"  : null,
    "Maryville University"  : null,
    "Metropolitan Community College"  : null,
    "Mineral Area College"  : null,
    "Mizzou University of Missouri"  : null,
    "Missouri State University"  : null,
    "Missouri Valley College"  : null,
    "Missouri Southern State University"  : null,
    "Missouri University of Science and Technology"  : null,
    "North Central Missouri College"  : null,
    "Nazarene Theological Seminary"  : null,
    "Northwest Missouri State University"  : null,
    "Ozarks Technical Community College"  : null,
    "Park University"  : null,
    "Rockhurst University"  : null,
    "Southwest Baptist University"  : null,
    "South Central Career Center"  : null,
    "Southeast Missouri State University"  : null,
    "Saint Louis University"  : null,
    "Saint Charles Community College"  : null,
    "Saint Louis Community College"  : null,
    "Truman State University"  : null,
    "University of Central Missouri"  : null,
    "University of Missouri Kansas City"  : null,
    "University of Missouri Saint Louis"  : null,
    "University of Missouri System"  : null,
    "Webster University"  : null,
    "Westminster College, Missouri"  : null,
    "Washington University in Saint Louis"  : null,
    "Alcorn State University"  : null,
    "Belhaven University"  : null,
    "Delta State University"  : null,
    "East Mississippi Community College"  : null,
    "Jackson State University"  : null,
    "Mississippi Gulf Coast Community College"  : null,
    "Mississippi State University"  : null,
    "Northeast Mississippi Community College"  : null,
    "The University of Mississippi"  : null,
    "Pearl River Community College"  : null,
    "Reformed Theological Seminary"  : null,
    "University of Mississippi Medical Center"  : null,
    "University of Southern Mississippi"  : null,
    "William Carey University"  : null,
    "Itawamba Community College"  : null,
    "Blackfeet Community College"  : null,
    "Carroll College"  : null,
    "Fort Peck Community College"  : null,
    "Flathead Valley Community College"  : null,
    "Miles Community College"  : null,
    "Montana State University"  : null,
    "Montana State University Billings"  : null,
    "Montana State University - Northern"  : null,
    "Montana Tech of the University of Montana"  : null,
    "Montana University System"  : null,
    "Rocky Mountain College"  : null,
    "University of Montana Helena College"  : null,
    "University of Montana"  : null,
    "University of Montana Western"  : null,
    "Asheville-Buncombe Technical Community College"  : null,
    "Alamance Community College"  : null,
    "Appalachian State University"  : null,
    "Bladen Community College"  : null,
    "Body Therapy Institute"  : null,
    "Campbell University"  : null,
    "Cape Fear Community College"  : null,
    "Charlotte School of Law"  : null,
    "Chowan University"  : null,
    "Central Piedmont Community College"  : null,
    "Craven Community College"  : null,
    "Davidson College"  : null,
    "Duke University"  : null,
    "Durham Technical Community College"  : null,
    "Elizabeth City State University"  : null,
    "East Carolina University"  : null,
    "Elon University"  : null,
    "Fayetteville Technical Community College"  : null,
    "Forsyth Technical Community College"  : null,
    "Gardner-Webb University"  : null,
    "Gaston College"  : null,
    "Guilford Technical Community College"  : null,
    "Heritage Bible College"  : null,
    "High Point University"  : null,
    "Isothermal Community College"  : null,
    "Lenoir Community College"  : null,
    "Lees McRae College"  : null,
    "Methodist University"  : null,
    "The University of Mount Olive"  : null,
    "Montgomery Community College"  : null,
    "North Carolina Central University"  : null,
    "North Carolina School of Science and Mathematics"  : null,
    "North Carolina State University"  : null,
    "North Carolina Wesleyan College"  : null,
    "New Life Theological Seminary"  : null,
    "University of North Carolina"  : null,
    "Piedmont Community College"  : null,
    "Pitt Community College"  : null,
    "Queens University of Charlotte"  : null,
    "Randolph Community College"  : null,
    "Roanoke-Chowan Community College"  : null,
    "Salem College"  : null,
    "Sampson Community College"  : null,
    "Sandhills Community College"  : null,
    "Saint Andrews University"  : null,
    "Southeastern Community College"  : null,
    "Southeastern Baptist Theological Seminary"  : null,
    "Shaw University"  : null,
    "Southwestern Community College"  : null,
    "South Piedmont Community College"  : null,
    "Stanly Community College"  : null,
    "Saint Augustine's University"  : null,
    "University of North Carolina at Chapel Hill"  : null,
    "University of North Carolina Asheville"  : null,
    "University of North Carolina Charlotte"  : null,
    "University of North Carolina Greensboro"  : null,
    "University of North Carolina Pembroke"  : null,
    "University of North Carolina School of the Arts"  : null,
    "University of North Carolina Wilmington"  : null,
    "Vance-Granville Community College"  : null,
    "Wake Technical Community College"  : null,
    "Warren Wilson College"  : null,
    "Western Carolina University"  : null,
    "Wake Forest University"  : null,
    "Western Piedmont Community College"  : null,
    "Winston-Salem State University"  : null,
    "Dakota College at Bottineau"  : null,
    "Mayville State University"  : null,
    "Minot State University"  : null,
    "North Dakota State University"  : null,
    "North Dakota University System"  : null,
    "Turtle Mountain Community College"  : null,
    "University of North Dakota"  : null,
    "United Tribes Technical College"  : null,
    "Valley City State University"  : null,
    "Williston State College"  : null,
    "Bellevue University"  : null,
    "Bryan College of Health Sciences"  : null,
    "Creighton University"  : null,
    "Chadron State College"  : null,
    "Concordia University Nebraska"  : null,
    "Joseph's College"  : null,
    "Little Priest Tribal College"  : null,
    "Mid-Plains Community College"  : null,
    "University of Nebraska"  : null,
    "Northeast Community College"  : null,
    "Union College"  : null,
    "University of Nebraska at Kearney"  : null,
    "University of Nebraska at Lincoln"  : null,
    "University of Nebraska Medical Center"  : null,
    "University of Nebraska Omaha"  : null,
    "Wayne State College"  : null,
    "Saint Anselm College"  : null,
    "Antioch University New England"  : null,
    "Community College System of New Hampshire"  : null,
    "Colby Sawyer College"  : null,
    "Dartmouth College"  : null,
    "Phillips Exeter Academy"  : null,
    "Granite State College"  : null,
    "Keene State College"  : null,
    "Manchester Community College"  : null,
    "Mount Washington College"  : null,
    "Nashua Community College"  : null,
    "New England College"  : null,
    "NHTI Concord's Community College"  : null,
    "Plymouth State University"  : null,
    "Rivier University"  : null,
    "Southern New Hampshire University"  : null,
    "University of New Hampshire"  : null,
    "White Mountains Community College"  : null,
    "Atlantic Cape Community College"  : null,
    "Burlington County College"  : null,
    "Bergen Community College"  : null,
    "Brookdale Community College"  : null,
    "Centenary College of New Jersey"  : null,
    "Drew University"  : null,
    "Eastwick College"  : null,
    "Fairleigh Dickinson University"  : null,
    "Felician College"  : null,
    "Fortis Institute"  : null,
    "Georgian Court University"  : null,
    "Kean University"  : null,
    "Mercer County Community College"  : null,
    "Middlesex County College"  : null,
    "Monmouth University"  : null,
    "Montclair State University"  : null,
    "New Jersey City University"  : null,
    "New Jersey Institute of Technology"  : null,
    "Ocean County College"  : null,
    "Princeton University"  : null,
    "Princeton Theological Seminary"  : null,
    "Ramapo College of New Jersey"  : null,
    "Raritan Valley Community College"  : null,
    "Rider University"  : null,
    "Rowan University"  : null,
    "Rutgers University"  : null,
    "Seton Hall University"  : null,
    "Stenotech Career Institute"  : null,
    "Stevens Institute of Technology"  : null,
    "Stockton College"  : null,
    "Sussex County Community College"  : null,
    "The College of New Jersey"  : null,
    "Thomas Edison State College"  : null,
    "William Paterson University"  : null,
    "County College of Morris"  : null,
    "Camden County College"  : null,
    "Passaic County Community College"  : null,
    "Ross University"  : null,
    "Central New Mexico"  : null,
    "Eastern New Mexico University"  : null,
    "New Mexico Highlands University"  : null,
    "New Mexico State University"  : null,
    "New Mexico State University Alamogordo"  : null,
    "New Mexico Institute of Mining and Technology"  : null,
    "Northern New Mexico College"  : null,
    "San Juan College"  : null,
    "Southwestern College"  : null,
    "Univeristy of New Mexico"  : null,
    "University of the Southwest"  : null,
    "College of Southern Nevada"  : null,
    "Great Basin College"  : null,
    "Pima Medical Institute"  : null,
    "Sierra Nevada College"  : null,
    "Truckee Meadows Community College"  : null,
    "University of Nevada Las Vegas"  : null,
    "University of Nevada Reno"  : null,
    "Western Nevada College"  : null,
    "Adelphi University"  : null,
    "University at Albany"  : null,
    "Alfred University"  : null,
    "The American Musical and Dramatic Academy"  : null,
    "ASA College"  : null,
    "Bard College"  : null,
    "Barnard College"  : null,
    "Binghamton University"  : null,
    "The College at Brockport"  : null,
    "University at Buffalo"  : null,
    "Buffalo State University"  : null,
    "Cazenovia College"  : null,
    "Clarkson University"  : null,
    "Clinton Community College"  : null,
    "The College of New Rochelle"  : null,
    "Cobleskill University"  : null,
    "Colgate University"  : null,
    "Columbia University in the City of New York"  : null,
    "Concordia College New York"  : null,
    "The Cooper Union"  : null,
    "Cornell University"  : null,
    "Cortland College"  : null,
    "The City University of New York"  : null,
    "The College of Westchester"  : null,
    "Daemen College"  : null,
    "Dominican College"  : null,
    "Delhi State University of New York"  : null,
    "Dowling College"  : null,
    "D'Youville College"  : null,
    "Erie Community College State University of New York"  : null,
    "Elim Bible Institute"  : null,
    "Elmira College"  : null,
    "Empire State College"  : null,
    "College of Environmental Science and Forestry"  : null,
    "Farmingdale State College"  : null,
    "Fashion Institute of Technology"  : null,
    "Finger Lakes Community College"  : null,
    "Fordham University"  : null,
    "Fredonia University"  : null,
    "Five Towns College"  : null,
    "Geneseo University"  : null,
    "Globe Institute of Technology"  : null,
    "The General Theological Seminary"  : null,
    "Hamilton College"  : null,
    "Hartwick College"  : null,
    "Herkimer College"  : null,
    "Hofstra University"  : null,
    "Hudson Valley Community College"  : null,
    "Hobart and William Smith Colleges"  : null,
    "Institute of Design and Construction"  : null,
    "Iona College"  : null,
    "Ithaca College"  : null,
    "The Jewish Theological Seminary"  : null,
    "The Juilliard School"  : null,
    "Keuka College"  : null,
    "Lehman College"  : null,
    "Le Moyne"  : null,
    "Lim College"  : null,
    "Long Island University"  : null,
    "Manhattan College"  : null,
    "Marist College"  : null,
    "Metropolitan College of New York"  : null,
    "Mercy College"  : null,
    "Marymount Manhattan College"  : null,
    "Monroe Community College"  : null,
    "Morrisville State College"  : null,
    "Mount Saint Marry College"  : null,
    "Icahn School of Medicine at Mount Sinai"  : null,
    "Manhattanville College"  : null,
    "Nazareth College"  : null,
    "Nassau Community College"  : null,
    "New Paltz"  : null,
    "The New School"  : null,
    "Niagara University"  : null,
    "Nyack College"  : null,
    "New York College of Health Professions"  : null,
    "New York Film Academy"  : null,
    "New York Institute of Technology"  : null,
    "New York University"  : null,
    "State University of New York at Oneonta"  : null,
    "State University of New York at Oswego"  : null,
    "Pace University"  : null,
    "Paul Smith's College"  : null,
    "State University of New York at Plattsburgh"  : null,
    "State University of New York at Potsdam"  : null,
    "Pratt Institute"  : null,
    "Purchase College"  : null,
    "Rochester Institute of Technology"  : null,
    "Roberts Wesleyan College"  : null,
    "University of Rochester"  : null,
    "Rensselaer Polytechnic Institute"  : null,
    "The Sages Colleges"  : null,
    "Saint Bonaventure University"  : null,
    "The New York Conservatory for Dramatic Arts"  : null,
    "Siena College"  : null,
    "Saint John Fisher College"  : null,
    "Skidmore College"  : null,
    "Sarah Lawrence College"  : null,
    "Saint Bernard's School of Theology and Ministry"  : null,
    "Saint John's University"  : null,
    "Saint Lawrence University"  : null,
    "Stony Brook University"  : null,
    "Stony Brook Medicine"  : null,
    "The College of Saint Rose"  : null,
    "State University of New York"  : null,
    "State University of New York at Adirondack"  : null,
    "State University of New Institute of Technology"  : null,
    "Jamestown Community College"  : null,
    "Orange County Community College"  : null,
    "Rockland Community College"  : null,
    "Suffolk County Community College"  : null,
    "Westchester Community College"  : null,
    "Syracuse University"  : null,
    "Tompkins Cortland Community College"  : null,
    "The Touro College and University System"  : null,
    "Touro College Jacob D. Fuchsberg Law Center"  : null,
    "Union College"  : null,
    "Upstate Medical University"  : null,
    "United States Military Academy West Point"  : null,
    "Utica College"  : null,
    "Vassar College"  : null,
    "Wagner College"  : null,
    "Wells College"  : null,
    "Yeshiva University"  : null,
    "Canton State University of New York"  : null,
    "Excelsior College"  : null,
    "Culinary Institute of America"  : null,
    "Ashland University"  : null,
    "Aultman College of Nursing and Health Sciences"  : null,
    "Belmont College"  : null,
    "Bowling Green State University"  : null,
    "Baldwin Wallace University"  : null,
    "Capital University"  : null,
    "Case Western Reserve University"  : null,
    "Cincinnati College of Mortuary Science"  : null,
    "Cedarville University"  : null,
    "Central State University"  : null,
    "Cincinnati State Technical and Community College"  : null,
    "Central Ohio Technical College"  : null,
    "Columbus State Community College"  : null,
    "Cleveland State University"  : null,
    "Western Reserve University"  : null,
    "Defiance College"  : null,
    "Denison University"  : null,
    "The University of Findlay"  : null,
    "Franklin University"  : null,
    "Heidelberg University"  : null,
    "Hiram College"  : null,
    "Hocking College"  : null,
    "John Carroll University"  : null,
    "Kettering College"  : null,
    "Kent State University"  : null,
    "Kenyon College"  : null,
    "Lakeland Community College"  : null,
    "Lima Central Catholic High School"  : null,
    "Lorain County Community College"  : null,
    "Malone University"  : null,
    "Marietta College"  : null,
    "Miami University"  : null,
    "University of Mount Union"  : null,
    "Mount Saint Joseph University"  : null,
    "Muskingum University"  : null,
    "Mount Vernon Nazarene University"  : null,
    "North Central State College"  : null,
    "Oberlin College and Conservatory"  : null,
    "Ohio University"  : null,
    "Ohio Dominican University"  : null,
    "Ohio State University"  : null,
    "Ohio Northern University"  : null,
    "Otterbein University"  : null,
    "Owens Community College"  : null,
    "Ohio Wesleyan University"  : null,
    "University of Rio Grande"  : null,
    "Shawnee State University"  : null,
    "Sinclair Community College"  : null,
    "Tiffin University"  : null,
    "Cuyahoga Community College"  : null,
    "The University of Akron"  : null,
    "University of Cincinnati"  : null,
    "University of Cincinnati Blue Ash"  : null,
    "University of Cincinnati Clermont"  : null,
    "University of Dayton"  : null,
    "Urbana University"  : null,
    "Ursuline College"  : null,
    "University of Toledo"  : null,
    "Walsh University"  : null,
    "Wilmington College"  : null,
    "Wittenberg University"  : null,
    "The College of Wooster"  : null,
    "Wright State University"  : null,
    "Xavier University"  : null,
    "Youngstown State University"  : null,
    "Ohio State University"  : null,
    "Cameron University"  : null,
    "Connors State College"  : null,
    "East Central University"  : null,
    "Langston University"  : null,
    "Mid-America Christian University"  : null,
    "Meridian Technology Center"  : null,
    "Northeastern State University"  : null,
    "Northwestern Oklahoma State University"  : null,
    "Oklahoma Christian University"  : null,
    "Oklahoma City Community College"  : null,
    "Oklahoma City University"  : null,
    "Oklahoma State University"  : null,
    "Oral Roberts University"  : null,
    "Oklahoma State University Institue of Technology"  : null,
    "Oklahoma State University"  : null,
    "The University of Oklahoma"  : null,
    "The University of Oklahoma Health Sciences Center"  : null,
    "Rose State College"  : null,
    "Rogers State University"  : null,
    "Southeastern Oklahoma State University"  : null,
    "Southwestern Christian University"  : null,
    "Southwestern Oklahoma State Univeristy"  : null,
    "Tulsa Community College"  : null,
    "University of Central Oklahoma"  : null,
    "University of Science and Arts of Oklahoma"  : null,
    "University of Tulsa"  : null,
    "Western Oklahoma State College"  : null,
    "Blue Mountain Community College"  : null,
    "Clatsop Community College"  : null,
    "Central Oregon Community College"  : null,
    "Columbia School of English"  : null,
    "Concordia University Portland Oregon"  : null,
    "Eastern Oregon University"  : null,
    "George Fox University"  : null,
    "Lane Community College"  : null,
    "Lewis and Clark"  : null,
    "Linfield College"  : null,
    "Linn-Benton Community College"  : null,
    "Marylhurst University"  : null,
    "National College of Natural Medicine"  : null,
    "Oregon Health and Science University"  : null,
    "Oregon State University"  : null,
    "Pacific University Oregon"  : null,
    "Portland Community College"  : null,
    "Portland State University"  : null,
    "Reed College"  : null,
    "Rogue Community College"  : null,
    "Southwestern Oregon Community College"  : null,
    "Southern Oregon University"  : null,
    "University of Oregon"  : null,
    "University of Portland"  : null,
    "Warner Pacific College"  : null,
    "Willamette University"  : null,
    "Western Oregon University"  : null,
    "Allegheny College"  : null,
    "Alvernia University"  : null,
    "Arcadia University"  : null,
    "Baptist Bible College & Seminary"  : null,
    "Butler County Community College"  : null,
    "Bloomsburg University"  : null,
    "Bryn Mawr College"  : null,
    "Bucknell University"  : null,
    "Bucks County Community College"  : null,
    "California University of Pennsylvania"  : null,
    "Carlow University"  : null,
    "Community College of Allegheny County"  : null,
    "Community College of Philadelphia"  : null,
    "Cedar Crest College"  : null,
    "Chatham University"  : null,
    "Chestnut Hill College"  : null,
    "Clarion University"  : null,
    "Carnegie Mellon University"  : null,
    "Delaware County Community College"  : null,
    "Delaware Valley College"  : null,
    "Dickinson College"  : null,
    "Drexel University"  : null,
    "Drexel University College of Medicine"  : null,
    "Duquesne University"  : null,
    "Eastern University"  : null,
    "Edinboro University"  : null,
    "Elizabethtown College"  : null,
    "Evangelical Seminary"  : null,
    "Franklin & Marshall College"  : null,
    "Saint Francis University"  : null,
    "Grove City College"  : null,
    "Geneva College"  : null,
    "Gettysburg College"  : null,
    "Harrisburg Area Community College"  : null,
    "Haverford College"  : null,
    "Holy Family University"  : null,
    "Indiana University of Pennsylvania"  : null,
    "Thomas Jefferson University"  : null,
    "Juniata College"  : null,
    "Keystone College"  : null,
    "King's College"  : null,
    "Kutztown University"  : null,
    "Lackawanna College"  : null,
    "Lafayette College"  : null,
    "Lancaster County Career and Technology Center"  : null,
    "Lancaster Theological Seminary"  : null,
    "La Roche College"  : null,
    "La Salle University"  : null,
    "Lehigh Carbon Community College"  : null,
    "Lake Erie College of Osteopathic Medicine"  : null,
    "Lehigh University"  : null,
    "Lock Haven University"  : null,
    "The Lincoln University"  : null,
    "Lansdale School of Business"  : null,
    "Lebanon Valley College"  : null,
    "Lycoming College"  : null,
    "Manor College"  : null,
    "Mansfield University"  : null,
    "Marywood University"  : null,
    "Montgomery County Community College"  : null,
    "Mercyhurst University"  : null,
    "Messiah College"  : null,
    "Millersville University"  : null,
    "Misericordia University"  : null,
    "Moravian College"  : null,
    "Mount Aloysius College"  : null,
    "Muhlenberg College"  : null,
    "Neumann University"  : null,
    "Northampton Community College"  : null,
    "Pennsylvania Gunsmith School"  : null,
    "Philadelphia College of Osteopathic Medicine"  : null,
    "Pennsylvania College of Technology"  : null,
    "Philadelphia University"  : null,
    "University of Pittsburgh"  : null,
    "Penn State University"  : null,
    "Reading Area Community College"  : null,
    "Robert Morris University"  : null,
    "Saint Vincent Seminary"  : null,
    "Salus University"  : null,
    "The University of Scranton"  : null,
    "Shippensburg University"  : null,
    "Saint Joseph's University"  : null,
    "Slippery Rock University"  : null,
    "Saint Vincent College"  : null,
    "Susquehanna University"  : null,
    "Swarthmore College"  : null,
    "Temple University"  : null,
    "The American College of Financial Services"  : null,
    "Thiel College"  : null,
    "University of the Arts"  : null,
    "University of Pennsylvania"  : null,
    "University of the Sciences in Philadelphia"  : null,
    "Valley Forge Christian College"  : null,
    "Villanova University"  : null,
    "Washington and Jefferson College"  : null,
    "Westmoreland County Community College"  : null,
    "West Chester University"  : null,
    "Westminster College"  : null,
    "Widener University"  : null,
    "Wilkes University"  : null,
    "Wilson College"  : null,
    "York College of Pennsylvania"  : null,
    "Pennsylvania Academy of the Fine Arts"  : null,
    "East Stroudsburg University"  : null,
    "Ursinus College"  : null,
    "DeSales University"  : null,
    "Lancaster Bible College"  : null,
    "Cheyney University of Pennsylvania"  : null,
    "Brown University"  : null,
    "Bryant University"  : null,
    "Community College of Rhode Island"  : null,
    "Johnson and Wales University"  : null,
    "New England Institute of Technology"  : null,
    "Providence College"  : null,
    "The University of Rhode Island"  : null,
    "Rhode Island College"  : null,
    "Rhose Island School of Design"  : null,
    "Roger Williams University"  : null,
    "University of Rhode Island"  : null,
    "Centura College"  : null,
    "The Citadel Military College of South Carolina"  : null,
    "Columbia International University"  : null,
    "Clemson University"  : null,
    "Coastal Carolina University"  : null,
    "College of Charleston"  : null,
    "Coker College"  : null,
    "Columbia College South Carolina"  : null,
    "Florence-Darlington Technical College"  : null,
    "Francis Marion University"  : null,
    "Forrest College"  : null,
    "Furman University"  : null,
    "Lander University"  : null,
    "Limestone College"  : null,
    "Midlands Technical College"  : null,
    "Medical University of South Carolina"  : null,
    "Newberry College"  : null,
    "North Greenville University"  : null,
    "Orangeburg-Calhoun Technical College"  : null,
    "Presbyterian College"  : null,
    "University of South Carolina"  : null,
    "South Carolina State University"  : null,
    "Sinte Gleska University"  : null,
    "Spartanburg Methodist College"  : null,
    "TriCounty Technical College"  : null,
    "University of South Carolina Aiken"  : null,
    "University of South Carolina Beaufort"  : null,
    "University of South Carolina Upstate"  : null,
    "Winthrop University"  : null,
    "Wofford College"  : null,
    "York Technical College"  : null,
    "Bob Jones University"  : null,
    "Anderson University"  : null,
    "Black Hills State University"  : null,
    "Dakota State University"  : null,
    "Dakota Wesleyan University"  : null,
    "Mount Marty College"  : null,
    "Northern State University"  : null,
    "South Dakota School of Mines and Technology"  : null,
    "South Dakota State University"  : null,
    "University of South Dakota"  : null,
    "University of Sioux Falls"  : null,
    "Western Dakota Technical Institute"  : null,
    "Austin Peay State University"  : null,
    "Belmont University"  : null,
    "Bryan College"  : null,
    "Christian Brothers University"  : null,
    "Carson-Newman University"  : null,
    "Columbia State Community College"  : null,
    "Cumberland University"  : null,
    "DeVry University"  : null,
    "East Tennessee State University"  : null,
    "Freed-Hardeman University"  : null,
    "Fisk University"  : null,
    "Huntington College of Health Sciences"  : null,
    "Hiwassee College"  : null,
    "Johnson University"  : null,
    "Jackson State Community College"  : null,
    "Lee University"  : null,
    "Lincoln Memorial University"  : null,
    "The LeMoyne-Owen College"  : null,
    "The University of Memphis"  : null,
    "Milligan College"  : null,
    "Middle Tennessee State University"  : null,
    "Nashville State Community College"  : null,
    "Pellissippi State Community College"  : null,
    "Rhodes College"  : null,
    "Roane State Community College"  : null,
    "Southern College of Optometry"  : null,
    "Sewanee The University of the South"  : null,
    "Southern Adventist University"  : null,
    "The University of Tennessee"  : null,
    "Southwest Tennessee Community College"  : null,
    "Tennessee State University"  : null,
    "Tennessee Technological University"  : null,
    "Tennessee Wesleyan College"  : null,
    "University of Tennessee Chattanooga"  : null,
    "University of Tennessee Health Science Center"  : null,
    "University of Tennessee Knoxville"  : null,
    "University of Tennessee Martin"  : null,
    "University of Tennessee Space Institute"  : null,
    "Union University"  : null,
    "Vanderbilt University"  : null,
    "Volunteer State Community College"  : null,
    "King University"  : null,
    "Abilene Christian University"  : null,
    "Alamo Colleges"  : null,
    "Alvin Community College"  : null,
    "Angelo State University"  : null,
    "Austin Community College District"  : null,
    "Austin College"  : null,
    "Austin Graduate School of Theology"  : null,
    "Baylor University"  : null,
    "Blinn College"  : null,
    "Brazosport College"  : null,
    "Brookhaven College"  : null,
    "Baptist Health System School of Health Professions"  : null,
    "Career Point College"  : null,
    "Cedar Valley College"  : null,
    "Coastal Bend College"  : null,
    "College of the Mainland"  : null,
    "Concordia University Texas"  : null,
    "Central Texas College"  : null,
    "Culinary Institute LeNotre"  : null,
    "Dallas Baptist University"  : null,
    "Del Mar College"  : null,
    "Dallas Nursing Institute"  : null,
    "El Paso Community College"  : null,
    "East Texas Baptist University"  : null,
    "Galen College of Nursing"  : null,
    "Galveston College"  : null,
    "Grayson College"  : null,
    "Houston Baptist University"  : null,
    "Houston Community College"  : null,
    "Hill College"  : null,
    "Howard College"  : null,
    "Howard Payne University"  : null,
    "Lamar University"  : null,
    "Lamar State College - Port Arthur"  : null,
    "Lubbock Christian University"  : null,
    "LeTourneau University"  : null,
    "Lamar Institute of Technology"  : null,
    "Lone Star College System"  : null,
    "Lamar State College - Orange"  : null,
    "McLennan Community College"  : null,
    "McMurry University"  : null,
    "Midland College"  : null,
    "Midwestern State University"  : null,
    "National American University"  : null,
    "North Central Texas College"  : null,
    "North American University"  : null,
    "North Lake College"  : null,
    "Odessa College"  : null,
    "Ogle School"  : null,
    "Our Lady of the Lake University"  : null,
    "Panola College"  : null,
    "Patty Hands Shelton School of Nursing"  : null,
    "Prairie View A&M University"  : null,
    "Rice University"  : null,
    "Richland College"  : null,
    "San Jacinto College"  : null,
    "Schreiner University"  : null,
    "Stephen F. Austin State University"  : null,
    "Sam Houston State University"  : null,
    "Southern Methodist University"  : null,
    "South Plains College"  : null,
    "South Texas College"  : null,
    "Southwestern University"  : null,
    "Seminary of the Southwest"  : null,
    "South Texas College of Law"  : null,
    "Saint Edward's University"  : null,
    "Saint Mary's University"  : null,
    "University of Saint Thomas"  : null,
    "Texas A&M Health Science Center"  : null,
    "Texas A&M International University"  : null,
    "Texas A&M University"  : null,
    "Texas A&M University Commerce"  : null,
    "Texas A&M University Corpus Christi"  : null,
    "Texas A&M University Kingsville"  : null,
    "Texas A&M University Texarkana"  : null,
    "Tarleton State University"  : null,
    "Texas Christian University"  : null,
    "Temple College"  : null,
    "Tyler Junior College"  : null,
    "Trinity University"  : null,
    "Texas State Technical College"  : null,
    "Texas Southern University"  : null,
    "Texas Tech University"  : null,
    "Texas Tech University Health Sciences Center"  : null,
    "Texas Woman's University"  : null,
    "Texas Chiropractic College"  : null,
    "Texas State University"  : null,
    "University of Dallas"  : null,
    "Universty of Houston"  : null,
    "University of Houston Clear Lake"  : null,
    "University of Houston Downtown"  : null,
    "University of the Incarnate Word"  : null,
    "University of Mary Hardin-Baylor"  : null,
    "University of North Texas"  : null,
    "University of North Texas Health Science Center"  : null,
    "University of Texas Arlington"  : null,
    "University of Texas Brownsville"  : null,
    "University of Texas Dallas"  : null,
    "University of Texas at El Paso"  : null,
    "University of Texas at Austin"  : null,
    "University of Texas Health Science Center Houston"  : null,
    "University of Texas Health Science Center San Antonio"  : null,
    "University of Texas Medical Branch at Galveston"  : null,
    "University of Texas Pan American"  : null,
    "University of Texas of the Permian Basin"  : null,
    "University of Texas at San Antonio"  : null,
    "University of Texas Southwestern Medical Center"  : null,
    "University of Texas at Tyler"  : null,
    "Valley Grande Institute"  : null,
    "Victoria College"  : null,
    "Wayland Baptist University"  : null,
    "Weatherford College"  : null,
    "West Texas A&M University"  : null,
    "University of the Virgin Islands"  : null,
    "Brigham Young University"  : null,
    "Dixie State University"  : null,
    "Salt Lake Community College"  : null,
    "Snow College"  : null,
    "Southern Utah University"  : null,
    "Utah State University"  : null,
    "University of Utah"  : null,
    "Utah Valley University"  : null,
    "Weber State University"  : null,
    "Western Governors University"  : null,
    "Averett University"  : null,
    "Christendom College"  : null,
    "Christopher Newport University"  : null,
    "Dabney S. Lancaster Community College"  : null,
    "Eastern Mennonite University"  : null,
    "Eastern Virginia Medical School"  : null,
    "Ferrum College"  : null,
    "Germanna Community College"  : null,
    "George Mason University"  : null,
    "Hampden-Sydney College"  : null,
    "The Institute for the Psychological Sciences"  : null,
    "James Madison University"  : null,
    "Liberty University"  : null,
    "Longwood University"  : null,
    "Marymount University"  : null,
    "New River Community College"  : null,
    "Norfolk State University"  : null,
    "Northern Virginia Community College"  : null,
    "Old Dominion University"  : null,
    "Radford University"  : null,
    "Randolph College"  : null,
    "Rappahannock Community College"  : null,
    "Regent University"  : null,
    "Reynolds Community College"  : null,
    "University of Richmond"  : null,
    "Randolph-Macon College"  : null,
    "Roanoke College"  : null,
    "Sentara College of Health Sciences"  : null,
    "Stratford University"  : null,
    "Shenandoah University"  : null,
    "Southern Virgina University"  : null,
    "Southwest Virgina Community College"  : null,
    "Tidewater Community College"  : null,
    "Thomas Nelson Community College"  : null,
    "University of Mary Washington"  : null,
    "University of Virginia's College at Wise"  : null,
    "Virginia's Community Colleges"  : null,
    "Virginia Commonwealth University"  : null,
    "Virgina Highlands Community College"  : null,
    "Virginia Institute of Marine Science"  : null,
    "University of Virginia"  : null,
    "Virginia Western Community College"  : null,
    "Virginia International University"  : null,
    "Virginia State University"  : null,
    "Virginia Polytechnic Institute and State University"  : null,
    "Virginia Union University"  : null,
    "Virginia Wesleyan College"  : null,
    "Washington and Lee University"  : null,
    "The College of William and Mary"  : null,
    "Castleton State College of Vermont"  : null,
    "Champlain College"  : null,
    "Green Mountain College"  : null,
    "Johnson State College"  : null,
    "Middlebury College"  : null,
    "New England Culinary Institute"  : null,
    "Norwich University"  : null,
    "School for International Training"  : null,
    "Saint Michael's College"  : null,
    "University of Vermont"  : null,
    "University of Vermont"  : null,
    "Vermont Law School"  : null,
    "Vermont Technical College"  : null,
    "Bennington College"  : null,
    "Bellevue College"  : null,
    "Big Bend Community College"  : null,
    "Cascadia Community College"  : null,
    "Centralia College"  : null,
    "Charter College"  : null,
    "Clark College"  : null,
    "Central Washington University"  : null,
    "DigiPen Institute of Technology"  : null,
    "Edmonds Community College"  : null,
    "Everett Community College"  : null,
    "The Evergreen State College"  : null,
    "Eastern Washington University"  : null,
    "Faith Evangelical College and Seminary"  : null,
    "Gonzaga University"  : null,
    "Green River Community College"  : null,
    "Highline College"  : null,
    "Mukogawa Fort Wright Institute"  : null,
    "North Seattle College"  : null,
    "Olympic College"  : null,
    "Peninsula College"  : null,
    "Perry Technical Institute"  : null,
    "Pacific Lutheran University"  : null,
    "Renton Technical College"  : null,
    "Seattle Central College"  : null,
    "Seattle University"  : null,
    "Shoreline Community College"  : null,
    "Seattle Institute of Oriental Medicine"  : null,
    "Skagit Valley College"  : null,
    "South Seattle College"  : null,
    "Spokane Falls Community College"  : null,
    "Seattle Pacific University"  : null,
    "Saint Martin's University"  : null,
    "University of Puget Sound"  : null,
    "University of Washington"  : null,
    "University of Washington Bothell"  : null,
    "Walla Walla University"  : null,
    "Whitman College"  : null,
    "Whitworth University"  : null,
    "Washington State University"  : null,
    "Wenatchee Valley College"  : null,
    "Walla Walla Community College"  : null,
    "Western Washington University"  : null,
    "Yakima Valley Community College"  : null,
    "University of Washington"  : null,
    "Alverno College"  : null,
    "Carroll University"  : null,
    "Carthage College"  : null,
    "Chippewa Valley Technical College"  : null,
    "Edgewood College"  : null,
    "Gateway Technical College"  : null,
    "The Institute of Beauty and Wellness"  : null,
    "Lawrence University"  : null,
    "Madison Area Technical College"  : null,
    "Marquette University"  : null,
    "Milwaukee Area Technical College"  : null,
    "Medical College of Wisconsin"  : null,
    "Milwaukee Institute of Art and Design"  : null,
    "Moraine Park Technical College"  : null,
    "Milwaukee School of Engineering"  : null,
    "Northland College"  : null,
    "Northcentral Technical College"  : null,
    "Northeast Wisconsin Technical College"  : null,
    "Silver Lake College of the Holy Family"  : null,
    "Saint Norbert College"  : null,
    "Cardinal Stritch University"  : null,
    "University of Wisconsin Colleges"  : null,
    "University of Wisconsin Eau Claire"  : null,
    "University of Wisconsin Extension"  : null,
    "University of Wisconsin Green Bay"  : null,
    "University of Wisconsin La Crosse"  : null,
    "University of Wisconsin Milwaukee"  : null,
    "University of Wisconsin Oshkosh"  : null,
    "University of Wisconsin Platteville"  : null,
    "University of Wisconsin River Falls"  : null,
    "University of Wisconsin Stevens Point"  : null,
    "University of Wisconsin Superior"  : null,
    "University of Wisconsin Whitewater"  : null,
    "Viterbo University"  : null,
    "Waukesha County Technical College"  : null,
    "University of Wisconsin, Madison"  : null,
    "Wisconsin Indianhead Technical College"  : null,
    "Wisconsin Lutheran College"  : null,
    "Wisconsin Technical College System"  : null,
    "Western Technical College"  : null,
    "American Public University System"  : null,
    "Concord University"  : null,
    "Eastern West Virgina Community and Technical College"  : null,
    "Fairmont State University"  : null,
    "Marshall University"  : null,
    "Ohio Valley University"  : null,
    "Pierpont Community and Technical College"  : null,
    "Shepherd University"  : null,
    "University of Charleston"  : null,
    "West Liberty University"  : null,
    "Wheeling Jesuit University"  : null,
    "West Virginia Northern Community College"  : null,
    "West Virginia State University"  : null,
    "West Virginia University"  : null,
    "West Virginia Wesleyan College"  : null,
    "Casper College"  : null,
    "Central Wyoming College"  : null,
    "National Outdoor Leadership School"  : null,
    "Northwest College"  : null,
    "Northern Wyoming Community College District"  : null,
    "University of Wyoming"  : null
}
